{
 "title": "Homer2",
 "description": "https://github.com/hkoosha/homer2\n\nAir quality monitoring on Raspberry Pi Pico: CO2, Humidity, Temperature, Volatile Organic Compounds, ..., you name it!",
 "tags": [
  "air-quality-monitoring",
  "homer2"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Polution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Env Particles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "ptc0_3{agent=\"homer2\"}",
     "legendFormat": "PTC 0.3"
    },
    { "expr": "ptc0_5", "legendFormat": "PTC 0.5" },
    { "expr": "ptc1_0", "legendFormat": "PTC 1.0" }
   ]
  },
  {
   "title": "Particulate Matter Concentration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "pm1_0{agent=\"homer2\"}",
     "legendFormat": "PM 1.0"
    },
    {
     "expr": "pm2_5{agent=\"homer2\"}",
     "legendFormat": "PM 2.5"
    },
    { "expr": "pm10_0", "legendFormat": "pm 10.0" }
   ]
  },
  {
   "title": "Env Particles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "ptc2_5{agent=\"homer2\"}",
     "legendFormat": "PTC 2.5"
    },
    { "expr": "ptc5_0", "legendFormat": "PTC 5.0" },
    { "expr": "ptc10_0", "legendFormat": "PTC 10.0" }
   ]
  },
  { "title": "Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "humidity{agent=\"homer2\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temperature{agent=\"homer2\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "pressure{agent=\"homer2\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Gases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "co2{agent=\"homer2\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "VOC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "voc_index{agent=\"homer2\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Gas Resistance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ohm" } },
   "targets": [
    {
     "expr": "gas_resistance{agent=\"homer2\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  }
 ]
}